#!/usr/bin/env python3
"""Render paper tables only from a complete locked run; no hand-filled scores."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent

def main():
 r=json.loads((HERE/'results.json').read_text());extra=json.loads((HERE/'additional_checks.json').read_text())
 if not r['complete']:raise RuntimeError('Matched run incomplete; do not publish partial results')
 data={(x['stream'],x['method']):x for x in r['matched_summary']}
 lines=[r'% Generated by exps/paper1_mechanism_audit/write_paper_tables.py',
 r'\begin{table*}[t]',r'\centering',r'\caption{Matched Gemma comparison on the fixed 60 documents per input condition. Each raw/gated pair shares one response.}',
 r'\label{tab:matched_mechanisms}',r'\small',r'\begin{tabular}{llrrrr}',r'\toprule',
 r'Context & Output & Ctrl. repair & Ctrl. F1 & Natural F1 & Natural exact \\',r'\midrule']
 for name,label in [('base','Base'),('diagnosis','Diagnostic'),('shacl_context','SHACL context')]:
  for post in ['raw','gate']:
   c=data['controlled',name+'_'+post];n=data['natural',name+'_'+post]
   lines.append(f"{label} & {post.title()} & {c['repair']:.4f} & {c['triple_f1']:.4f} & {n['triple_f1']:.4f} & {n['exact_match']:.4f} \\\\")
 lines += [r'\bottomrule',r'\end{tabular}',r'\end{table*}',
           r'\begin{table*}[t]',r'\centering',r'\caption{Final-run request costs. Means include retries and rate-pacing waits; source preparation and executor queue time are excluded.}',r'\label{tab:matched_cost}',r'\small',r'\begin{tabular}{llrrrr}',r'\toprule',r'Input & Context & Calls & Input tokens & Output tokens & Wall (s) \\',r'\midrule']
 for row in r['costs']:
  name={'base':'Base','diagnosis':'Diagnostic','shacl_context':'SHACL'}[row['arm']]
  st={'controlled':'Controlled','natural':'Natural'}[row['stream']]
  lines.append(f"{st} & {name} & {row['calls']:.2f} & {row['prompt_tokens']:.0f} & {row['completion_tokens']:.0f} & {row['wall_seconds']:.2f} \\\\")
 lines += [r'\bottomrule',r'\end{tabular}',r'\end{table*}',r'\begin{table*}[t]',r'\centering',r'\caption{Input-derived diagnostic scaling. Memory is peak new batch allocation in MiB; source texts are shared.}',r'\label{tab:diagnostic_scaling}',r'\small',r'\begin{tabular}{rrrrr}',r'\toprule',r'Triples & Documents & Full (ms) & Local (ms) & Allocation (MiB) \\',r'\midrule']
 for row in extra['diagnostic_scaling']:
  lines.append(f"{row['triples']:,} & {row['documents']:,} & {row['full_diagnostic_ms']:.2f} & {row['one_doc_update_ms']:.3f} & {row['new_graph_alloc_peak_mb']:.2f} \\\\")
 lines += [r'\bottomrule',r'\end{tabular}',r'\end{table*}']
 text='\n'.join(lines)+'\n'
 text=text.replace('\\begin{tabular}', '\\resizebox{\\textwidth}{!}{%\n\\begin{tabular}').replace('\\end{tabular}', '\\end{tabular}%\n}')
 (ROOT/'paper1/sections/audit_generated.tex').write_text(text)
 print('Wrote 3 tables from complete archived results')
if __name__=='__main__':main()
